version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      time: "12:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    target-branch: main

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "00:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    target-branch: main
